#---------------------------------------------------------------------------------------------------------
# CONFIGURACIÓN DE JPA
#---------------------------------------------------------------------------------------------------------
spring.datasource.url=jdbc:h2:mem:inventario;INIT=CREATE SCHEMA IF NOT EXISTS inventario
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#---------------------------------------------------------------------------------------------------------
# CONFIGURACION DE LOGS
#---------------------------------------------------------------------------------------------------------
spring.main.banner-mode=console
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG